### ISSUE TITLE
typo in blog for "ev-join-processor"

### ISSUE THREAD

**Issue by phderome** [mkuthan/example-kafkastreams#1]
you pass it as first of 5 parameters as literal String to constructor `EvJoinProcessor` in the blog but in your working code it is only required in calls to `addProcessor` and `addStateStore`. In code you use symbolic variable names rather than String literal but you have 4 parameters (presumably correct).

**Comment by mkuthan** [comment]
Thank You for finding typo in the blog post, fixed :) Code is always source of truth.
